[settings]
quiet = true
task_output = "interleave"
experimental = true
aqua.registries = ["https://github.com/KnickKnackLabs/bats-core"]

[plugins]
shiv = "https://github.com/KnickKnackLabs/vfox-shiv"

[tools]
"aqua:KnickKnackLabs/bats-core" = "1.14.0-kkl.3"
"aqua:nushell/nushell" = "0.115.1"
"aqua:shenwei356/rush" = "0.11.0"
ast-grep = "0.45.3"
gum = "2.0.1"
jq = "1.8.2"

# Knick Knack Labs
"shiv:codebase" = "0.5"
"shiv:ctl" = "0.3"
"shiv:readme" = "0.3"

[_.codebase]
name = "comments"
lint = ["@all"]
